version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working-directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            flake8 --statistics
            pytest -v